# Generated by Django 4.1.3 on 2022-11-13 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='residencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idResidencia', models.CharField(max_length=31)),
                ('nombreDueño', models.CharField(max_length=30)),
                ('fonoDueño', models.CharField(max_length=15)),
                ('emailDueño', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='correspondencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaRecepcion', models.DateTimeField(max_length=10)),
                ('nombreConserje', models.CharField(max_length=30)),
                ('nombreRemitente', models.CharField(max_length=30)),
                ('nombreDestinatario', models.CharField(max_length=30)),
                ('Estado', models.BooleanField()),
                ('id_Residencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.residencia')),
            ],
        ),
    ]
